package com.myteam.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Объект HW")
public class HelloWorldObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u041F\u0435\u0440\u0432\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430")
	private java.lang.String firstStr;
	@org.kie.api.definition.type.Label(value = "\u0412\u0442\u043E\u0440\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430")
	private java.lang.String secondStr;
	@org.kie.api.definition.type.Label(value = "\u041F\u043E\u043B\u043D\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430")
	private java.lang.String fullStr;

	public HelloWorldObject() {
	}

	public java.lang.String getFirstStr() {
		return this.firstStr;
	}

	public void setFirstStr(java.lang.String firstStr) {
		this.firstStr = firstStr;
	}

	public java.lang.String getSecondStr() {
		return this.secondStr;
	}

	public void setSecondStr(java.lang.String secondStr) {
		this.secondStr = secondStr;
	}

	public java.lang.String getFullStr() {
		return this.fullStr;
	}

	public void setFullStr(java.lang.String fullStr) {
		this.fullStr = fullStr;
	}

	public HelloWorldObject(java.lang.String firstStr,
			java.lang.String secondStr, java.lang.String fullStr) {
		this.firstStr = firstStr;
		this.secondStr = secondStr;
		this.fullStr = fullStr;
	}

}