package com.myteam.helloworld;

import com.myteam.helloworld.HelloWorldObject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Объект HW с локализацией языка")
public class HelloWorldObjectWithLocale extends HelloWorldObject
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u0426\u0435\u043B\u0435\u0432\u043E\u0439 \u044F\u0437\u044B\u043A")
	private java.lang.String targetLang;

	public HelloWorldObjectWithLocale() {
	}

	public java.lang.String getTargetLang() {
		return this.targetLang;
	}

	public void setTargetLang(java.lang.String targetLang) {
		this.targetLang = targetLang;
	}

	public HelloWorldObjectWithLocale(java.lang.String targetLang) {
		this.targetLang = targetLang;
	}

}