package com.myteam.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Объект HW с локализацией языка")
public class HelloWorldObjectWithLocale extends HelloWorldObject
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Целевой язык")
	private java.lang.String targetLang;

	@org.kie.api.definition.type.Label(value = "\u042F\u0437\u044B\u043A \u043E\u0440\u0438\u0433\u0438\u043D\u0430\u043B\u0430")
	private java.lang.String originalLang;

	public HelloWorldObjectWithLocale() {
	}

	public java.lang.String getTargetLang() {
		return this.targetLang;
	}

	public void setTargetLang(java.lang.String targetLang) {
		this.targetLang = targetLang;
	}

	public java.lang.String getOriginalLang() {
		return this.originalLang;
	}

	public void setOriginalLang(java.lang.String originalLang) {
		this.originalLang = originalLang;
	}

	public HelloWorldObjectWithLocale(java.lang.String targetLang,
			java.lang.String originalLang) {
		this.targetLang = targetLang;
		this.originalLang = originalLang;
	}

}