package com.myteam.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Объект HW с локализацией языка")
public class HelloWorldObjectWithLocale extends HelloWorldObject
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Язык оригинала")
	private java.lang.String originalLang;

	public HelloWorldObjectWithLocale() {
	}

	public java.lang.String getOriginalLang() {
		return this.originalLang;
	}

	public void setOriginalLang(java.lang.String originalLang) {
		this.originalLang = originalLang;
	}

	public HelloWorldObjectWithLocale(java.lang.String originalLang) {
		this.originalLang = originalLang;
	}

}